name: freebuddy
description: Free (and open source) buddy app for bluetooth headphones

publish_to: "none" # Prevent accidental publication to pub.dev

version: 0.2.0+11

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  app_settings: ^6.1.1
  async: ^2.11.0
  collection: ^1.19.0
  crclib: ^3.0.0
  device_info_plus: ^9.1.1
  dynamic_color: ^1.7.0
  equatable: ^2.0.7
  file_picker: ^10.1.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  go_router: ^13.0.0
  home_widget: ^0.7.0
  intl: ^0.19.0
  logger: ^2.5.0
  material_color_utilities: ^0.11.0
  material_symbols_icons: ^4.2801.0
  meta: ^1.16.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.0
  provider: ^6.1.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  stream_channel: ^2.1.0
  streaming_shared_preferences: ^2.0.0
  the_last_bluetooth:
    git:
      url: https://github.com/TheLastGimbus/the_last_bluetooth.git
      ref: master
  url_launcher: ^6.3.0
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main

dependency_overrides:
  logger: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  icon_font_generator: ^4.0.0

icon_font:
  input_svg_dir: "assets/app_icons/vector/"
  output_font_file: "fonts/FreebuddyIcons.otf"
  output_class_file: "lib/gen/freebuddy_icons.dart"
  class_name: "FreebuddyIcons"
  format: true
  font_name: "FreebuddyIcons"

flutter_launcher_icons:
  image_path: "assets/app_icons/ic_launcher.png"
  android: "ic_launcher"
  adaptive_icon_background: "#ffefefef"
  adaptive_icon_foreground: "assets/app_icons/ic_launcher_adaptive_fore.png"

flutter_native_splash:
  color: "#efefef"
  color_dark: "#0f0f0f"
  image: "assets/app_icons/ic_launcher.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - "assets/app_icons/ic_launcher.png"
    - "assets/headphones/huawei/freebuds3i_og.png"

  fonts:
    - family: FreebuddyIcons
      fonts:
        - asset: "fonts/FreebuddyIcons.otf"

    - family: MaterialIcons
      fonts:
        - asset: "name: freebuddy
description: Free (and open source) buddy app for bluetooth headphones

publish_to: "none" # Prevent accidental publication to pub.dev

version: 0.2.0+11

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  app_settings: ^6.1.1
  async: ^2.11.0
  collection: ^1.19.0
  crclib: ^3.0.0
  device_info_plus: ^9.1.1
  dynamic_color: ^1.7.0
  equatable: ^2.0.7
  file_picker: ^10.1.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  go_router: ^13.0.0
  home_widget: ^0.7.0
  intl: ^0.19.0
  logger: ^2.5.0
  material_color_utilities: ^0.11.0
  material_symbols_icons: ^4.2801.0
  meta: ^1.16.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.0
  provider: ^6.1.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  stream_channel: ^2.1.0
  streaming_shared_preferences: ^2.0.0
  the_last_bluetooth:
    git:
      url: https://github.com/TheLastGimbus/the_last_bluetooth.git
      ref: master
  url_launcher: ^6.3.0
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main

dependency_overrides:
  logger: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  icon_fsets/app_icons/ic_launcher.png"
  android: "ic_launcher"
  adaptive_icon_background: "#ffefefef"
  adaptive_icon_foreground: "assets/app_icons/ic_launcher_adaptive_fore.png"

flutter_native_splash:
  color: "#efefef"
  color_dark: "#0f0f0f"
  image: "assets/app_icons/ic_launcher.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - "assets/app_icons/ic_launcher.png"
    - "assets/headphones/huawei/freebuds3i_og.png"

  fonts:
    - family: FreebuddyIcons
      fonts:
        - asset: "fonts/FreebuddyIcons.otf"

    - family: MaterialIcons
      fonts:
        - asset: "fonts/MaterialIcons-Regular.otf"

    - family: MaterialSymbolsOutlined
      fonts:
        - asset: "fonts/MaterialSymbolsOutlined.ttf"

    - family: MaterialSymbolsRounded
      fonts:
        - asset: "fonts/MaterialSymbolsRounded.ttf"

    - family: MaterialSymbolsSharp
      fonts:
        - asset: "fonts/MaterialSymbolsSharp.ttf"
