name: Build and Release

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: true
        default: 'v0.2.0'
      build_format:
        description: 'Choose the build format (APK, AAB, or both)'
        required: true
        default: 'both'
        options:
          - 'apk'
          - 'aab'
          - 'both'

env:
  flutter_channel: "any"
  GH_TOKEN: ${{ secrets.GH_PAT }}  # Cambié a GH_PAT en lugar de GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Limpiar el nombre del tag y extraerlo de las entradas
      - name: Clean tag name
        id: clean_tag
        run: |
          TAG="${{ github.event.inputs.tag }}"
          # Eliminar el prefijo "v" si existe
          CLEAN_TAG=$(echo "$TAG" | sed 's/^v//')
          echo "tag=$CLEAN_TAG" >> $GITHUB_ENV
      
      # Parsear fvm para obtener la versión de flutter
      - name: Parse fvm to set flutter version
        run: echo "flutter_version=$(cat .fvm/fvm_config.json | jq -r .flutterSdkVersion)" >> $GITHUB_ENV

      # Cache de Flutter
      - name: Cache Flutter
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}-${{ env.flutter_channel }}
      
      # Instalar Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: ${{ env.flutter_channel }}
      
      # Construir APK y AAB
      - name: Build APK & AAB with signing
        uses: NiklasLehnfeld/flutter-android-build-action@v2
        id: android-build
        with:
          release: true
          keystore: ${{ secrets.KEYSTORE }}
          keystore-pwd: "${{ secrets.KEYSTORE_PWD }}"
          key-pwd: "${{ secrets.KEY_PWD }}"

      # Renombrar los archivos APK y AAB
      - name: Rename APK & AAB
        run: |
          mv ${{ steps.android-build.outputs.apk-path }} ./FreeBuddy-${{ env.tag }}.apk
          mv ${{ steps.android-build.outputs.aab-path }} ./FreeBuddy-${{ env.tag }}.aab

      # Obtener el changelog asociado al tag
      - name: Get changelog
        run: |
          echo "Debug: Using tag ${{ env.tag }}"
          python scripts/get_changelog.py --version ${{ env.tag }} > ./body-file.txt
      
      # Crear la release en GitHub
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_PAT }}  # Usando GH_PAT para autenticación
          body_path: ./body-file.txt
          files: |
            ${{ github.event.inputs.build_format == 'apk' && './FreeBuddy-${{ env.tag }}.apk' || '' }}
            ${{ github.event.inputs.build_format == 'aab' && './FreeBuddy-${{ env.tag }}.aab' || '' }}
            ${{ github.event.inputs.build_format == 'both' && './FreeBuddy-${{ env.tag }}.apk' || '' }}
            ${{ github.event.inputs.build_format == 'both' && './FreeBuddy-${{ env.tag }}.aab' || '' }}
          fail_on_unmatched_files: true
