name: Build and publish new release on version tag

on:
  push:
    branches:
      - 'master'  # Ejecutar al hacer un commit en la rama master
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'  # Trigger para tags de versión
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: true
        default: 'v2.0.0'
      build_format:
        description: 'Choose the build format (APK, AAB, or both)'
        required: true
        default: 'both'
        options:
          - 'apk'
          - 'aab'
          - 'both'

env:
  flutter_channel: "any"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Limpiar el nombre del tag y extraerlo de las entradas
      - name: Clean tag name
        id: clean_tag
        run: |
          TAG="${{ github.event.inputs.tag }}"
          # Eliminar el prefijo "v" si existe
          CLEAN_TAG=$(echo "$TAG" | sed 's/^v//')
          echo "tag=$CLEAN_TAG" >> $GITHUB_ENV
      
      # Parsear fvm para obtener la versión de flutter
      - name: Parse fvm to set flutter version
        run: echo "flutter_version=$(cat .fvm/fvm_config.json | jq -r .flutterSdkVersion)" >> $GITHUB_ENV

      # Cache de Flutter
      - name: Cache Flutter
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}-${{ env.flutter_channel }}
      
      # Instalar Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: ${{ env.flutter_channel }}
      
      # Construir APK y/o AAB con firma
      - name: Build APK & AAB with signing
        uses: NiklasLehnfeld/flutter-android-build-action@v2
        id: android-build
        with:
          release: true
          keystore: ${{ secrets.KEYSTORE }}
          keystore-pwd: "${{ secrets.KEYSTORE_PWD }}"
          key-pwd: "${{ secrets.KEY_PWD }}"
          build-type: ${{ github.event.inputs.build_format }}  # Usar 'build-type' en lugar de 'build-format'
          flutter-args: "--no-tree-shake-icons"  # Añadir el argumento para no eliminar íconos no usados
      
      # Renombrar los archivos APK y AAB
      - name: Rename APK & AAB
        run: |
          if [[ "${{ github.event.inputs.build_format }}" == "apk" || "${{ github.event.inputs.build_format }}" == "both" ]]; then
            mv ${{ steps.android-build.outputs.apk-path }} ./FreeBuddy-${{ env.tag }}.apk
          fi
          if [[ "${{ github.event.inputs.build_format }}" == "aab" || "${{ github.event.inputs.build_format }}" == "both" ]]; then
            mv ${{ steps.android-build.outputs.aab-path }} ./FreeBuddy-${{ env.tag }}.aab
          fi

      # Obtener el changelog asociado al tag
      - name: Get changelog
        run: python scripts/get_changelog.py --version ${{ env.tag }} > ./body-file.txt
      
      # Crear la release en GitHub
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./body-file.txt
          files: |
            ./FreeBuddy-${{ env.tag }}.apk
            ./FreeBuddy-${{ env.tag }}.aab
          fail_on_unmatched_files: true
